### ISSUE TITLE
Change reading estimates to round up

### ISSUE THREAD

**Issue by Jesse-Na** [Andyctct/Hugo-Personal-Site#1]
In your post "Do birds ever sing the same song twice?" your website says it is a 0 minute read, but I think that is misleading. It seems to be rounding down, but I think you should round it up. It would greatly enhance the reader's quality of life. Thanks!

**Comment by Andyctct** [comment]
Disagree. Issue resolved.

**Comment by Andyctct** [comment]
Reader's issue is stupid.

**Comment by Jesse-Na** [comment]
DO NOT CONTRIBUTE TO THIS REPO, OWNER IS VERY UNRESPONSIVE

**Comment by Andyctct** [comment]
Reviewer is butthurt because his trivial issues were rightfully rejected. Now trying to impair future business, sad.
